### PR TITLE
More "s"

### PR DESCRIPTION
**Pull request by leangjia**
Sorry about the "S".

### CODE REVIEW

**Comment by leangjia** [comment]
@wowas18 wowas18

**Comment by wowas18** [comment]
Can't merge this changes because mro_maps is depend on web_maps.
So no need change __manifest__.py 
Please create new pull request for translation but without changes in __manifest__.py

**Comment by leangjia** [comment]
@wowas18 
Thank you for your reply. 
Well, https://github.com/codup/odoo-tools/web_map, not have "s".
mro_maps manifest.py is web_maps, more "s".
That's mro_maps installation failed reason.

**Comment by wowas18** [comment]
@leangjia 
That module depends on other module **web_maps**
https://www.odoo.com/apps/modules/12.0/web_maps/

**Pull request closed without merging**
