### PR TITLE
improve mro module description

### LINKED ISSUE #12: mro.order: date_planned vs. date_scheduled clarification
could you add a help for the two fields `date_planned` and `date_scheduled` the names have very close semantics for me and I totally don't understand what they are used for.

### PR DESCRIPTION
**Pull request by gurneyalex**
used http://codup.com/en/component/content/article/93-applications/maintenance/192-mro-pm.html#comment-79 as base to improve mro module description

closes #12

### CODE REVIEW

**Comment by wowas18** [comment]
I don't think that  `__openerp__.py`  - right place for detailed decription.
Use `doc` like this https://github.com/odoo/odoo/tree/9.0/addons/account/doc

**Comment by gurneyalex** [comment]
the description in __openerp__.py (or in v8 the contents of the README.txt file) is displayed in the settings / modules form view which makes it a very easy way to provide the developers / users with a quick doc. This is the current practise among the Odoo Community Association addons. 

I won't push on this, though, if you don't like the idea.

**Comment by wowas18** [comment]
I think `description` in the settings, it's short and general text about module. Usefull when you first time install it. 
But you try add `detailed` manual about how work with it. I think that for `detailed` manual, folder `doc` is right place. Because if add all `detailed` information it will be like book. What you think about it?

**Comment by gurneyalex** [comment]
I have no objection :smile_cat:

**Pull request closed without merging**
